config/routes.rb
Rails.application.routes.draw do
  root "kittens#index"
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: %i[show edit update destroy]

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:notice] = "You added a kitten! Great job!"
      redirect_to @kitten
    else
      flash.now[:alert] = "Something went wrong! Maybe you gave it negative cuteness?"
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @kitten.update(kitten_params)
      flash[:notice] = "Kitten updated successfully!"
      redirect_to @kitten
    else
      flash.now[:alert] = "Update failed. Are you sure this kitten is soft enough?"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten.destroy
    flash[:notice] = "Kitten deleted. Monster!"
    redirect_to kittens_path
  end

  private

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with(model: @kitten, local: true) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </p>
  <p>
    <%= f.label :cuteness %><br>
    <%= f.number_field :cuteness %>
  </p>
  <p>
    <%= f.label :softness %><br>
    <%= f.number_field :softness %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>
<%= render "form" %>
<%= link_to "Back", kittens_path %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>

<%= link_to "Add a new Kitten", new_kitten_path %>

<ul>
  <% @kittens.each do |kitten| %>
    <li>
      <%= link_to kitten.name, kitten %> (Age: <%= kitten.age %>)
      <%= link_to "Edit", edit_kitten_path(kitten) %> |
      <%= link_to "Delete", kitten, method: :delete, data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>
<%= render "form" %>
<%= link_to "Back", kittens_path %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>

<%= link_to "Edit", edit_kitten_path(@kitten) %> |
<%= link_to "Delete", @kitten, method: :delete, data: { confirm: "Are you sure?" } %> |
<%= link_to "Back to All", kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Odin Kittens</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>
<body>
  <% flash.each do |key, msg| %>
    <p><strong><%= key.capitalize %>:</strong> <%= msg %></p>
  <% end %>
  <%= yield %>
</body>
</html>